### ISSUE TITLE
SSL integration with OtlpExporter in OpenTelemetry Collector.

### ISSUE THREAD

**Issue by kowshikn** [opendistro-for-elasticsearch/data-prepper#203]
Trace Analytics Pipeline offers OTLP source with SSL/TLS. Users should use this with `secure` option in the [OtlpExporter](https://github.com/open-telemetry/opentelemetry-collector/tree/master/exporter/otlpexporter) in the [Otel collector](https://github.com/open-telemetry/opentelemetry-collector). For unknown reason the OtlpExporter in Otel Collector doesn't work with secure option starting v0.12.0. Have already created an [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/2054) in the upstream project.

This is issue is to track the above issue in our end.

**Comment by kowshikn** [comment]
This is still open, no update from the community. Will see if we can escalate this and hopefully they will fix this after GA at least.

**Comment by wrijeff** [comment]
Likely caused by using self-signed certs, I ran into this while attempting to use an OTel Exporter to hit an ALB configured to use TLS. 

Their [TLS config docs](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/README.md) show a new "insecure_skip_verify" parameter which skips the cert verification. This setting appears in release 0.16.0 and up. 

Changed my docker-compose file to use 0.17.0, added "insecure_skip_verify: true", confirmed I was able to successfully export trace data through the ALB.
